### ISSUE TITLE
entity counts are wrong

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_cv_xray#12]
http://160.36.205.61:8095/organism/Fraxinus/excelsior?tripal_pane=group_ontologies

At  first glance it looks like counts are happening for child terms but not grandchild terms.

edit: yep, definitely whats happening.

<img width="819" alt="screen shot 2018-04-11 at 12 21 54 pm" src="https://user-images.githubusercontent.com/7063154/38629772-f5d24886-3d82-11e8-8460-b7220fc7d895.png">

**Comment by bradfordcondon** [comment]
flipping the subject nad object in the indexer did not fix this issue.

**Comment by almasaeed2010** [comment]
This should be solved using the new indexer. My only concern is whether we duplicate entity_id,cvterm_id mappings. We can check that by adding a unique constraint on the table and see if it fails to do so.

**Comment by almasaeed2010** [comment]
So we do have duplicates. To check run:

```sql
select entity_id, cvterm_id, count(*)
  from tripal_cvterm_entity_linker
  group by cvterm_id, entity_id
  having count(*) > 1
```

```sql
select count(*) from (
 select entity_id, cvterm_id, count(*) 
   from tripal_cvterm_entity_linker 
   group by cvterm_id, entity_id 
   having count(*) > 1
) counter_tmp;

 count  
--------
 605210
(1 row)
```

so there are 605210 duplicate entity_id -> cvterm_id mappings
