### ISSUE TITLE
GO field only has one of three domains represented

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_cv_xray#23]
http://160.36.205.61:8095/organism/Fraxinus/excelsior?tripal_pane=group_ontologies

fairly certain this is a bug.

**Comment by bradfordcondon** [comment]
* There are no index entries for the other two root terms 
* there are, however, index entries for direct children of those root terms
   - for example, binding [GO:0005488] (55)
* These assocations show up as expected (see below)

<img width="796" alt="screen shot 2018-04-24 at 2 14 25 pm" src="https://user-images.githubusercontent.com/7063154/39205864-e7f52a0c-47c9-11e8-9022-23224dc6dff1.png">

**Comment by almasaeed2010** [comment]
Molecular function started at /root/nohup.out

**Comment by almasaeed2010** [comment]
Fixed.
