### ISSUE TITLE
Support collections

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/tripal_cv_xray#30]
Add collections support in "Matching Entities" page

**Comment by jwest60** [comment]
this feature is ready for testing [here](https://github.com/statonlab/tripal_cv_xray/tree/collections)

adds the option to create a collection on the matching entities page
![image](https://user-images.githubusercontent.com/32902460/41373095-4db13424-6f1d-11e8-9307-27a090a8f744.png)

the button takes you to a form where you can name the collection and give a description and choose what fields you want

![image](https://user-images.githubusercontent.com/32902460/41373181-87a0809a-6f1d-11e8-871f-5134580de427.png)

**Comment by bradfordcondon** [comment]
you got it, thanks joe.
