### ISSUE TITLE
create a new table that stores admin configuration

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_cv_xray#43]
for example, that the admin wants to index biomaterials and GO.

Then, the module can implement hooks to listen for entity creation/deletion and update the index as necessary.

see also:

https://github.com/tripal/tripal_elasticsearch/issues/191

**Comment by bradfordcondon** [comment]
https://github.com/statonlab/tripal_cv_xray/commit/a8eeb30e78547150591d95653535ed3760c2c592

@almasaeed2010 question: should i submit a single job per entity?  That's the easiest way how its set up.

Alternatives:
* Update index per entity directly (not by submtting a job)
* Create a new handler class that compiles inserted entities and launches jobs in chunks, like the Dispatcher class?

**Comment by almasaeed2010** [comment]
I think a job per entity is perfectly fine. This is how it's done in ES and it is working great!

**Comment by bradfordcondon** [comment]
added with #47
