### ISSUE TITLE
cvtermbrowser field should return null if there are no terms mapped

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_cv_xray#57]
see 

https://github.com/statonlab/hardwoods_site/issues/330

if no records for any terms in an ontology, the field should return null so it doesnt show up.

**Comment by bradfordcondon** [comment]
`      $results = ((int) $query->countQuery()->execute()->fetchField()) > 1;` as expected we attempt to do this.  why isnt it working?

**Comment by almasaeed2010** [comment]
should we unset the field? Like you showed me the other day

**Comment by bradfordcondon** [comment]
yes!  let's do that.  I'm on it if you want.

**Comment by bradfordcondon** [comment]
resolved by joining on index table.
