### ISSUE TITLE
Drush compatibility for installing

### ISSUE THREAD

**Issue by bordercases** [statonlab/tripal_cv_xray#60]
Most Tripal plugins are available through Drush, however this isn't listed on the Drupal website yet

**Comment by almasaeed2010** [comment]
Hello @bordercases we still don't have an account with Drupal that allows us to publish plugins on the main Drupal repository where `drush` can find them.

Do you need help installing this tool without drush?

Thanks!

**Comment by bradfordcondon** [comment]
hi @bordercases 

we've added some minimal support for drush by putting a project up on the drupal site:  
https://www.drupal.org/project/tripal_cv_xray
we're not sure how much we'll be able to support it but if its critical for youre site let us know and we'll do our bset.
